#!/usr/bin/env bash

# Mac OS X configuration
#
# This configuration applies to the latest version of macOS (currently 11.3),
# and sets up preferences and configurations for all the built-in services and
# apps. Third-party app config should be done elsewhere.
#
# Options:
#   --no-restart: Don't restart any apps or services after running the script.
#
# If you want to figure out what default needs changing, do the following:
#
#   1. `cd /tmp`
#   2. Store current defaults in file: `defaults read > before`
#   3. Make a change to your system.
#   4. Store new defaults in file: `defaults read > after`
#   5. Diff the files: `diff before after`
#
# @see: http://secrets.blacktree.com/?showapp=com.apple.finder
# @see: https://github.com/herrbischoff/awesome-macos-command-line
#
# @author Jeff Geerling

# Warn that some commands will not be run if the script is not run as root.
if [[ $EUID -ne 0 ]]; then
  RUN_AS_ROOT=false
  printf "Certain commands will not be run without sudo privileges. To run as root, run the same command prepended with 'sudo', for example: $ sudo $0\n\n" | fold -s -w 80
else
  RUN_AS_ROOT=true
  # Update existing `sudo` timestamp until `.osx` has finished
  while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &
fi

###############################################################################
# General UI/UX                                                               #
###############################################################################

# Expand save panel by default
defaults read NSGlobalDomain NSNavPanelExpandedStateForSaveMode

# Expand print panel by default
defaults read NSGlobalDomain PMPrintingExpandedStateForPrint

# Save to disk (not to iCloud) by default
defaults read NSGlobalDomain NSDocumentSaveNewDocumentsToCloud

# Automatically quit printer app once the print jobs complete
defaults read com.apple.print.PrintingPrefs "Quit When Finished"

# Restart automatically if the computer freezes
if [[ "$RUN_AS_ROOT" = true ]]; then
  systemsetup -setrestartfreeze on
fi

# Disable smart quotes as they’re annoying when typing code
defaults read NSGlobalDomain NSAutomaticQuoteSubstitutionEnabled

# Disable smart dashes as they’re annoying when typing code
defaults read NSGlobalDomain NSAutomaticDashSubstitutionEnabled

# Set background to dark-grey color
#osascript -e 'tell application "Finder" to set desktop picture to POSIX file "/System/Library/Desktop Pictures/Solid Colors/Stone.png"'

###############################################################################
# Trackpad, mouse, keyboard, Bluetooth accessories, and input                 #
###############################################################################

# Trackpad: Haptic feedback (light, silent clicking)
defaults read com.apple.AppleMultitouchTrackpad FirstClickThreshold
defaults read com.apple.AppleMultitouchTrackpad ActuationStrength

# Trackpad: map bottom right corner to right-click (requires restart!)
defaults read com.apple.driver.AppleBluetoothMultitouch.trackpad TrackpadRightClick
defaults read com.apple.AppleMultitouchTrackpad TrackpadRightClick
defaults read com.apple.AppleMultitouchTrackpad TrackpadCornerSecondaryClick
defaults read NSGlobalDomain ContextMenuGesture

# Disable press-and-hold for keys in favor of key repeat
defaults read NSGlobalDomain ApplePressAndHoldEnabled

# Set a blazingly fast keyboard repeat rate, and make it happen more quickly.
# (The KeyRepeat option requires logging out and back in to take effect.)
defaults read NSGlobalDomain InitialKeyRepeat
defaults read NSGlobalDomain KeyRepeat

# Disable auto-correct
defaults read NSGlobalDomain NSAutomaticSpellingCorrectionEnabled

###############################################################################
# Screen                                                                      #
###############################################################################

# Save screenshots to Downloads folder.
defaults read com.apple.screencapture location

# Save screenshots in PNG format (other options: BMP, GIF, JPG, PDF, TIFF)
defaults read com.apple.screencapture type

# Disable shadow in screenshots
defaults read com.apple.screencapture disable-shadow

###############################################################################
# Finder                                                                      #
###############################################################################

# Set Desktop as the default location for new Finder windows
# For other paths, use `PfLo` and `file:///full/path/here/`
defaults read com.apple.finder NewWindowTarget
defaults read com.apple.finder NewWindowTargetPath

# Show icons for hard drives, servers, and removable media on the desktop
defaults read com.apple.finder ShowExternalHardDrivesOnDesktop
defaults read com.apple.finder ShowHardDrivesOnDesktop
defaults read com.apple.finder ShowMountedServersOnDesktop
defaults read com.apple.finder ShowRemovableMediaOnDesktop

# Finder: show hidden files by default
# defaults read com.apple.finder AppleShowAllFiles

# Finder: show all filename extensions
defaults read NSGlobalDomain AppleShowAllExtensions

# Finder: show status bar
defaults read com.apple.finder ShowStatusBar

# Finder: allow text selection in Quick Look
defaults read com.apple.finder QLEnableTextSelection

# Display full POSIX path as Finder window title
defaults read com.apple.finder _FXShowPosixPathInTitle

# When performing a search, search the current folder by default
defaults read com.apple.finder FXDefaultSearchScope

# Disable the warning when changing a file extension
defaults read com.apple.finder FXEnableExtensionChangeWarning

# Enable spring loading for directories
defaults read NSGlobalDomain com.apple.springing.enabled

# Remove the spring loading delay for directories
defaults read NSGlobalDomain com.apple.springing.delay

# Avoid creating .DS_Store files on network volumes
defaults read com.apple.desktopservices DSDontWriteNetworkStores

# Enable snap-to-grid for icons on the desktop and in other icon views
/usr/libexec/PlistBuddy -c "Print :DesktopViewSettings:IconViewSettings:arrangeBy grid" ~/Library/Preferences/com.apple.finder.plist
/usr/libexec/PlistBuddy -c "Print :FK_StandardViewSettings:IconViewSettings:arrangeBy grid" ~/Library/Preferences/com.apple.finder.plist
/usr/libexec/PlistBuddy -c "Print :StandardViewSettings:IconViewSettings:arrangeBy grid" ~/Library/Preferences/com.apple.finder.plist

# Set the size of icons on the desktop and in other icon views
/usr/libexec/PlistBuddy -c "Print :DesktopViewSettings:IconViewSettings:iconSize 64" ~/Library/Preferences/com.apple.finder.plist
/usr/libexec/PlistBuddy -c "Print :FK_StandardViewSettings:IconViewSettings:iconSize 64" ~/Library/Preferences/com.apple.finder.plist
/usr/libexec/PlistBuddy -c "Print :StandardViewSettings:IconViewSettings:iconSize 64" ~/Library/Preferences/com.apple.finder.plist

# Use column view in all Finder windows by default
# Four-letter codes for the other view modes: `icnv`, `Nlsv`, `clmv`, `Flwv`
defaults read com.apple.finder FXPreferredViewStyle

# Show the ~/Library folder
chflags nohidden ~/Library

###############################################################################
# Dock, Dashboard, and hot corners                                            #
###############################################################################

# Set the icon size of Dock items
defaults read com.apple.dock tilesize

# Speed up Mission Control animations
defaults read com.apple.dock expose-animation-duration

# Make Dock icons of hidden applications translucent
defaults read com.apple.dock showhidden

# Enable the 'reduce transparency' option. Save GPU cycles.
defaults read com.apple.universalaccess reduceTransparency

# Hot corners
# Possible values:
#  0: no-op
#  2: Mission Control
#  3: Show application windows
#  4: Desktop
#  5: Start screen saver
#  6: Disable screen saver
#  7: Dashboard
# 10: Put display to sleep
# 11: Launchpad
# 12: Notification Center
# Bottom right screen corner → Mission Control
defaults read com.apple.dock wvous-br-corner
defaults read com.apple.dock wvous-br-modifier
# Top right screen corner → Put display to sleep
defaults read com.apple.dock wvous-tr-corner
defaults read com.apple.dock wvous-tr-modifier
# Bottom left screen corner → Desktop
defaults read com.apple.dock wvous-bl-corner
defaults read com.apple.dock wvous-bl-modifier

###############################################################################
# Safari & WebKit                                                             #
###############################################################################

# Enable the Develop menu and the Web Inspector in Safari
defaults read com.apple.Safari IncludeDevelopMenu
defaults read com.apple.Safari WebKitDeveloperExtrasEnabledPreferenceKey
defaults read com.apple.Safari com.apple.Safari.ContentPageGroupIdentifier.WebKit2DeveloperExtrasEnabled

# Add a context menu item for showing the Web Inspector in web views
defaults read NSGlobalDomain WebKitDeveloperExtras

###############################################################################
# Mail                                                                        #
###############################################################################

# Copy email addresses as `foo@example.com` instead of `Foo Bar <foo@example.com>` in Mail.app
defaults read com.apple.mail AddressesIncludeNameOnPasteboard

###############################################################################
# Spotlight                                                                   #
###############################################################################

if [[ "$RUN_AS_ROOT" = true ]]; then
  # Disable Spotlight indexing for any volume that gets mounted and has not yet
  # been indexed before.
  # Use `sudo mdutil -i off "/Volumes/foo"` to stop indexing any volume.
  sudo defaults read /.Spotlight-V100/VolumeConfiguration

  # Restart spotlight
  #killall mds > /dev/null 2>&1
fi

###############################################################################
# Activity Monitor                                                            #
###############################################################################

# Show the main window when launching Activity Monitor
defaults read com.apple.ActivityMonitor OpenMainWindow

# Show all processes in Activity Monitor
defaults read com.apple.ActivityMonitor ShowCategory

###############################################################################
# Messages                                                                    #
###############################################################################

# Disable smart quotes as it’s annoying for messages that contain code
defaults read com.apple.messageshelper.MessageController SOInputLineSettings

# Disable continuous spell checking
defaults read com.apple.messageshelper.MessageController SOInputLineSettings

###############################################################################
# Kill/restart affected applications                                          #
###############################################################################

# Restart affected applications if `--no-restart` flag is not present.
if [[ ! ($* == *--no-restart*) ]]; then
  for app in "cfprefsd" "Dock" "Finder" "Mail" "SystemUIServer" "Terminal"; do
    echo "killall \"${app}\""
    #killall "${app}" > /dev/null 2>&1
  done
fi

printf "Please log out and log back in to make all settings take effect.\n"
